export const appointments = [
    {
      id: 1,
      appointment_id: 1123,
      center : "Medanta",
      patient_name: "Himanshu",
      patient_phone: "98726335445",
      appointment_date: "29/08/2000",
      appointment_time: "3:04pm",
      charges: 3000,
      payment_status: "Pending",
      appointment_status: "Pending",
      before_weight: 72.5,
      after_weight: 68.2,
    },
  
    {
      id: 2,
      appointment_id: 1123,
      center : "Medanta",
      patient_name: "Himanshu",
      patient_phone: "98726335445",
      appointment_date: "29/08/2000",
      appointment_time: "3:04pm",
      charges: 3000,
      payment_status: "Complete",
      appointment_status: "onGoing",
      before_weight: 72.5,
      after_weight: 68.2,
    },
  
    {
      id: 3,
      appointment_id: 1123,
      center : "Medanta",
      patient_name: "Himanshu",
      patient_phone: "98726335445",
      appointment_date: "29/08/2000",
      appointment_time: "3:04pm",
      charges: 3000,
      payment_status: "Pending",
      appointment_status: "onGoing",
      before_weight: 72.5,
      after_weight: 68.2,
    },
  
    {
      id: 4,
      appointment_id: 1123,
      center : "Medanta",
      patient_name: "Himanshu",
      patient_phone: "98726335445",
      appointment_date: "29/08/2000",
      appointment_time: "3:04pm",
      charges: 3000,
      payment_status: "Completed",
      appointment_status: "Cancelled",
      before_weight: 72.5,
      after_weight: 68.2,
    },
  
    {
      id: 5,
      appointment_id: 1123,
      center : "Medanta",
      patient_name: "Himanshu",
      patient_phone: "98726335445",
      appointment_date: "29/08/2000",
      appointment_time: "3:04pm",
      charges: 3000,
      payment_status: "Pending",
      appointment_status: "Completed",
      before_weight: 72.5,
      after_weight: 68.2,
    },
  ];
  
  