export const centerData = [
    {
      _id : 1,
      name: "Center 1",
      email: "abc@gmail.com",
      contact_no: "1234567890",
      address: "c-15",
      city : "delhi",
      state : "delhi",
      pincode : "123456",
      latitude : "tets",
      longitude : "test",
      total_beds : 5,
      status : 2,
      introduction : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tortor libero, efficitur id faucibus consectetur, molestie nec dolor. Pellentesque ac leo efficitur, scelerisque massa eu, vestibulum augue. In ac nisi at lorem dictum iaculis vel id velit. Maecenas eu odio porta, vulputate nisl nec, bibendum augue. Fusce sit amet quam ornare, varius nisi sit amet, venenatis eros. Proin auctor venenatis lectus, eu molestie mauris. Etiam ut ante nisi. Etiam diam purus, egestas id ipsum sed, euismod tempus ipsum. Sed convallis lorem sed dapibus auctor. Nunc malesuada nibh at velit pellentesque, pellentesque tempus mauris interdum. Curabitur scelerisque sed dolor vitae posuere. Nullam auctor ligula sit amet urna malesuada, consequat dignissim nunc rhoncus. Nullam ac congue lectus.",
      verify_status : 2,
    },
    {
        _id : 2,
        name: "Center 1",
        email: "abc@gmail.com",
        contact_no: "1234567890",
        address: "c-15",
        city : "delhi",
        state : "delhi",
        pincode : "123456",
        latitude : "tets",
        longitude : "test",
        total_beds : 5,
        status : 1,
        introduction : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tortor libero, efficitur id faucibus consectetur, molestie nec dolor. Pellentesque ac leo efficitur, scelerisque massa eu, vestibulum augue. In ac nisi at lorem dictum iaculis vel id velit. Maecenas eu odio porta, vulputate nisl nec, bibendum augue. Fusce sit amet quam ornare, varius nisi sit amet, venenatis eros. Proin auctor venenatis lectus, eu molestie mauris. Etiam ut ante nisi. Etiam diam purus, egestas id ipsum sed, euismod tempus ipsum. Sed convallis lorem sed dapibus auctor. Nunc malesuada nibh at velit pellentesque, pellentesque tempus mauris interdum. Curabitur scelerisque sed dolor vitae posuere. Nullam auctor ligula sit amet urna malesuada, consequat dignissim nunc rhoncus. Nullam ac congue lectus.",
        verify_status : 1,
      },
      {
        _id : 3,
        name: "Center 1",
        email: "abc@gmail.com",
        contact_no: "1234567890",
        address: "c-15",
        city : "delhi",
        state : "delhi",
        pincode : "123456",
        latitude : "tets",
        longitude : "test",
        total_beds : 5,
        status : 1,
        introduction : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tortor libero, efficitur id faucibus consectetur, molestie nec dolor. Pellentesque ac leo efficitur, scelerisque massa eu, vestibulum augue. In ac nisi at lorem dictum iaculis vel id velit. Maecenas eu odio porta, vulputate nisl nec, bibendum augue. Fusce sit amet quam ornare, varius nisi sit amet, venenatis eros. Proin auctor venenatis lectus, eu molestie mauris. Etiam ut ante nisi. Etiam diam purus, egestas id ipsum sed, euismod tempus ipsum. Sed convallis lorem sed dapibus auctor. Nunc malesuada nibh at velit pellentesque, pellentesque tempus mauris interdum. Curabitur scelerisque sed dolor vitae posuere. Nullam auctor ligula sit amet urna malesuada, consequat dignissim nunc rhoncus. Nullam ac congue lectus.",
        verify_status : 1,
      },
   
  ];